### ISSUE TITLE
core_thread_push() doesn't support empty string

### ISSUE THREAD

**Issue by tomaskrizek** [DNS-OARC/dnsjit#139]
Currently, it's not possible to push an empty string to a thread, because it has zero length. Attempting to do so triggers a fatal error.

Passing an empty string may be useful in some cases, e.g. when using it as a default value for getopt.
```
#!/usr/bin/env dnsjit
local thread = require("dnsjit.core.thread")
local getopt = require("dnsjit.lib.getopt").new({
	{ "s", "string", "", "optional string", "?" },
})
getopt:parse()

local opt_string = getopt:val("string")
local thr = thread.new()
thr:push(opt_string)
```
```
core/thread.c[176] core.thread[0xdeadbeef] fatal: len is zero
```

**Comment by jelu** [comment]
I can't remember but I think there was a reason, anyway, changing to allow an empty string will add a lot of more checks everywhere else. I'm not against anyone changing this, just never thought about pushing getopt's like this.

You could push `0` (int) in-place of an empty string or use `"\0"` as default.

Love the dead beef btw :D

**Comment by tomaskrizek** [comment]
Sure, there are ways around it. I'll probably use `"\0"` if I'll need to. In the end, I didn't need to push empty string, since I had a different default.

I was just a bit surprised with this behavior when I encountered this issue. But it's not a high priority and can probably even stay as-is if there's some reason for it.

**Comment by jelu** [comment]
It has a bit to do with the struct being passed that carries the values, see `struct core_thread_item` and  `function Thread:pop()`. Also, `malloc(0)`, does it work? Anyway, `"\0"` is probably what would be needed to be done internally so I'll close this.
