### ISSUE TITLE
version module

### ISSUE THREAD

**Issue by tomaskrizek** [DNS-OARC/dnsjit#169]
Since dnsjit is a library and the scripts built on top of it might require a specific new-enough version of dnsjit, it'd be useful if there was an easy way to check version, e.g.:

```
local version = require("dnsjit.core.version")
print(version.major)    -- 1
print(version.minor)    -- 1
print(version.release)  -- 0
version.compare(">=1.1.0", fatal=false)
```

List of useful operators: `>`, `<`, `>=`, `<=`, `!=`, `==`, `=`

**Comment by jelu** [comment]
I don't know what you mean about `version.release`, there is no such versioning label/value.

Globals already exists, see `src/globals.c`.

Backward compatibility MUST be retained between major versions and I've been thinking about having `dnsjit0`, `dnsjit1`, `dnsjit2` etc as major version aliases.

Scripts should not care about minor and patch version.

**Comment by tomaskrizek** [comment]
`version.patch`, not `version.release` :)

The issue I have is this - dnssim in the next version will introduce `https2()` method which wasn't available before. I'd like to just do a version check to see if its available. Same for potential future changes to behaviour of methods.

I don't think these changes are significant enough to warrant a major version of dnssim, that's why I'd be interested in having more granular version comparison.

**Comment by jelu** [comment]
`dnssim` has no version, if you want to version it you will need to remove it from this base and add it as a Lua extension/.so

You can version check right now with the globals or do a `pcall()`.

**Comment by tomaskrizek** [comment]
I didn't know about the `DNSJIT_*VERSION` globals, seems like a solution. Nevertheless, I'd appreciate a convenience lua function that could compare the version against a given version string, so I don't have to copy-paste it everywhere where it's needed.
