### ISSUE TITLE
input: pcap decompression

### ISSUE THREAD

**Issue by tomaskrizek** [DNS-OARC/dnsjit#177]
Continuing the discussion from https://github.com/DNS-OARC/dnsjit/issues/120#issuecomment-700792072 .

Compressing PCAPs could save significant storage space (4-6x less file size with my dataset) and with fast enough decompression (lz4, zstd), the performance impact might be a decent tradeoff.

Both lz4 and zstd support streaming decompression (`LZ4_decompress_safe_continue()`, `ZSTD_decompressStream()`) which could be suitable for dnsjit input.

I've been considering on ways of implementing this in a way that is flexible enough to support future additions of other compression algorithms. Here's my idea, please let me know if it would be suitable:

- introduce new object type which would be a generic buffer, e.g. `dnsjit.core.object.buffer`
- implement the compression in a dedicated input component, e.g. `dnsjit.input.zstd`. This component would produce `dnsjit.core.object.buffer` obejcts.
- create a PCAP-parsing component similar to `dnsjit.input.fpcap`, which would pull data from a producer (zstd / lz4 input component) instead of a file. I'm not sure if this component should be classified as filter or input.

The other option to implement this would be to create a single input component which would both decompress a given file _and_ parse it as PCAP. This wouldn't require the addition of buffer-like object, but it could lead to some code duplication.

**Comment by jelu** [comment]
Been giving this some thought and I don't think we need to make it this complex, I also do not want to extend the object chain any longer then it is (it's a bit weird and hard to understand as it is).

I think we should start smaller instead, lets add this compression support to `fpcap` and see how it works. That already have the PCAP parser so there isn't really any code duplication. And if this is also implemented in `mmpcap` then I think it's going to be quite different API to the compression libraries as it will be working on mapped memory. `pcap` (libpcap) is more there for the capture on interfaces then for reading from files.

I suggest you add `open_lz4()` and/or `open_zstd()` to `fpcap` and we take it from there to finalize the changes.
