### ISSUE TITLE
OpenResty LuaJIT / luajit 2.1 compatibility

### ISSUE THREAD

**Issue by diizzyy** [DNS-OARC/dnsjit#215]
Hi,

I just tried to build this with OpenResty's fork v2.1-20210510 and the ffi test in src/gen-compat.lua seems to return different results compared to LuaJIT 2.0.5.

https://github.com/DNS-OARC/dnsjit/blob/develop/src/gen-compat.lua#L23

Using OpenResty code path is used (ssize_t) while it isn't for LuaJIT (long).

At least on FreeBSD 13 that causes build issues while it builds if you many force the same code path as for LuaJIT.

```
--- core/compat.o ---
In file included from core/compat.c:25:
In file included from ./core/compat.hh:37:
In file included from /usr/include/unistd.h:39:
In file included from /usr/include/sys/types.h:49:
/usr/include/sys/_pthreadtypes.h:67:27: error: typedef redefinition with different types ('struct pthread *' vs 'struct pthread')
typedef struct  pthread                 *pthread_t;
                                         ^
./core/compat.hh:28:43: note: previous definition is here
typedef struct pthread { uint64_t a[1]; } pthread_t;
                                          ^
In file included from core/compat.c:25:
In file included from ./core/compat.hh:37:
In file included from /usr/include/unistd.h:39:
In file included from /usr/include/sys/types.h:49:
/usr/include/sys/_pthreadtypes.h:71:32: error: typedef redefinition with different types ('struct pthread_mutex *' vs 'struct pthread_mutex')
typedef struct  pthread_mutex           *pthread_mutex_t;
                                         ^
./core/compat.hh:24:49: note: previous definition is here
typedef struct pthread_mutex { uint64_t a[1]; } pthread_mutex_t;
                                                ^
In file included from core/compat.c:25:
In file included from ./core/compat.hh:37:
In file included from /usr/include/unistd.h:39:
In file included from /usr/include/sys/types.h:49:
/usr/include/sys/_pthreadtypes.h:73:31: error: typedef redefinition with different types ('struct pthread_cond *' vs 'struct pthread_cond')
typedef struct  pthread_cond            *pthread_cond_t;
                                         ^
./core/compat.hh:20:48: note: previous definition is here
typedef struct pthread_cond { uint64_t a[1]; } pthread_cond_t;
                                               ^
3 errors generated.
*** [core/compat.o] Error code 1

make[5]: stopped in /usr/ports/dns/dnsjit/work/dnsjit-1.2.1/src
1 error
```

This is on FreeBSD 13-STABLE and using dnsjit 1.2.1

**Comment by jelu** [comment]
So what is the issue here really?

Is it that gen-compat is different?

Or that you get build error using unsupported OpenResty?

**Comment by diizzyy** [comment]
Using OpenResty you get
```
#include <unistd.h>
typedef ssize_t luajit_ssize_t;
```
in src\core\compat.hh which makes the build fail

LuaJIT 
```
typedef long luajit_ssize_t;
```
which works for both libraries as far as compiling goes at least

OpenResty compatibility would be nice as it supports more architectures than LuaJIT such as aarch64/arm64 (http://wiki.luajit.org/architecture-support) .

**Comment by jelu** [comment]
Can you test removing `print("#include <unistd.h>")` from `gen-compat.lua`?

**Comment by diizzyy** [comment]
That single change results in
```
--- core/compat.o ---
In file included from core/compat.c:25:
./core/compat.hh:37:9: error: unknown type name 'ssize_t'
typedef ssize_t luajit_ssize_t;
        ^
1 error generated.
*** [core/compat.o] Error code 1
```
Importing https://github.com/DNS-OARC/dnsjit/pull/216 does however fix build issue.
Thanks for looking into this!

**Comment by jelu** [comment]
Yeah, I saw the problem after I posted that question.

So the issue you hit isn't really related to OpenResty or FreeBSD, it could happen elsewhere.

About OpenResty support, if you wish to have specific features or support like OpenResty I'm more then happy to receive, review and merge patches for that. Or you can also fund the work (see [Funding Development](https://www.dns-oarc.net/oarc/software)).
