### ISSUE TITLE
Built error on FreeBSD

### ISSUE THREAD

**Issue by Jakker** [DNS-OARC/dnsjit#220]
Ti have it build on FreeBSD so it can be packaged for FreeBSD users, I had to make a patch. See the [this PR](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261274) for details.

**Comment by Jakker** [comment]
I don't understand this either, wil send you the logs when I have more time. Not, I didn't created the port/package, I jusr wanted to upgrade the drool port.

**Comment by Jakker** [comment]
Oops, didn't want to cloe

**Comment by diizzyy** [comment]
I think it's a llvm 12+ issue

**Comment by jelu** [comment]
Can any of you try to add `static` to the lines instead of removing `inline`?

So it's `static inline ...`

**Comment by Jakker** [comment]
Gave it a quick try and yes, that seems to work
