### ISSUE TITLE
blocked SIGPIPE causes uninterruptible dnsjit scripts

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnsjit#234]
Normally scripts which use stdout can be terminated by signal SIGPIPE, i.e. when another tool in the pipeline cuts the output etc.

Dnsjit blocks SIGPIPE unconditionally and this causes scripts to run until they terminate for other reasons, even if the all the output is being dropped.

This is causing trouble in long testing pipelines which do decompress & process as separate steps in individual processes.

A minimal example:

File /tmp/out.lua
```lua
local output = io.stdout
while (true)
do
	output:write("bla\n")
end
```

LuaJIT behavior:
```console
$ time luajit /tmp/out.lua | head -n1
bla

real	0m0.002s
user	0m0.002s
sys	0m0.000s
```

Dnsjit behavior:
```
$ time dnsjit /tmp/out.lua | head -n1
bla
^Ccore fatal: signal 2

real	0m3.654s
user	0m3.622s
sys	0m0.030s
```

I would submit MR to unblock SIGPIPE, but I'm not sure why generic block for (almost) all signals was put in place.

Current behavior stems from this piece of code:
```c
     48 int main(int argc, char* argv[])
     49 {
...
     60     sigfillset(&set);
     61     if ((err = pthread_sigmask(SIG_BLOCK, &set, 0))) {
     62         glfatal("Unable to set blocked signals with pthread_sigmask()");
     63         return 2;
     64     }
     65 
     66     sigemptyset(&set);
     67     sigaddset(&set, SIGTERM);
     68     sigaddset(&set, SIGQUIT);
     69     sigaddset(&set, SIGINT);
     70 
     71     if ((err = pthread_create(&sighthr, 0, _sighthr, &set))) {
     72         glfatal("Unable to start signal thread with pthread_create()");
     73         return 2;
     74     }
```

**Comment by jelu** [comment]
`dnsjit` goes wroooooom! no time to stop for signals! :smile: will fix

**Comment by jelu** [comment]
@pspacek @tkrizek please test this :)

**Comment by tkrizek** [comment]
Signals are now working as expected. We've just had to ignore `SIGPIPE` in DNS Shotgun to keep its prior behavior, otherwise all looks good. Thanks!
