### ISSUE TITLE
ipsplit tests fails due to endianess

### ISSUE THREAD

**Issue by jelu** [DNS-OARC/dnsjit#250]
@nicki-krizek can you fix ipsplit tests using overwrite or make overwrite handle endianess correctly?

They fail on other endian systems such as s390x:
https://bugzilla.redhat.com/show_bug.cgi?id=2323980#c7

**Comment by nicki-krizek** [comment]
Heh, I actually found a note about this issue when I wrote these tests a few years back: https://github.com/DNS-OARC/dnsjit/blob/develop/src/test/test_ipsplit.lua#L2

This doesn't matter for the `ipsplit` filter functionality (as noted in the [docs](https://github.com/DNS-OARC/dnsjit/blob/develop/src/filter/ipsplit.lua#L116), the bytes are written in host order).

On BE-platform, I'd recommend disabling / commenting out the related checks if needed, or just skipping the ipsplit test. IMO this is not worth fixing. It could be commented out in the upstream test suite if you insist.

**Comment by jelu** [comment]
I know it doesn't matter for ipsplit, but what is the purpose of overwrite
and shouldn't it be consistent no matter the byte order?

**Comment by jelu** [comment]
OK. I'll fix the test and mark the overwrite function as non-portable (once
I'm back).
