### ISSUE TITLE
make install skips lua libraries

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dnsjit#63]
It seems that simple `make install` does not install all necessary files:

```
$ ./dumpdns-qr.lua /home/pspacek/pcaps/test.pcap
<< dnsjit v0.9.3 https://github.com/DNS-OARC/dnsjit/issues >>
core critical: ./dumpdns-qr.lua: ./dumpdns-qr.lua:9: module 'dnsjit.core.object' not found:
	no field package.preload['dnsjit.core.object']
	no file './dnsjit/core/object.lua'
	no file '/usr/share/luajit-2.1.0-beta3/dnsjit/core/object.lua'
	no file '/usr/local/share/lua/5.1/dnsjit/core/object.lua'
	no file '/usr/local/share/lua/5.1/dnsjit/core/object/init.lua'
	no file '/usr/share/lua/5.1/dnsjit/core/object.lua'
	no file '/usr/share/lua/5.1/dnsjit/core/object/init.lua'
	no file './dnsjit/core/object.so'
	no file '/usr/lo
```

```
$ ls /usr/local/share/lua/5.1/dnsjit
ls: cannot access '/usr/local/share/lua/5.1/dnsjit': No such file or directory
```

I did not specify any arguments to `configure`/`make`/`make install`.

**Comment by pspacek** [comment]
Version 163de2c7fbe0d6b94675195fb6578ba4ce80ef32

**Comment by jelu** [comment]
Uhm, strange, all libraries are compiled into the binary. What OS?

**Comment by jelu** [comment]
And full `configure && make && make install` output please.

**Comment by jelu** [comment]
Works for me:
```
$ sh autogen.sh
$ ./configure
$ make
$ sudo make install
$ which dnsjit
/usr/local/bin/dnsjit
$ examples/dumpdns-qr.lua ~/dns.pcap 
<< dnsjit v0.9.3 https://github.com/DNS-OARC/dnsjit/issues >>
src	dst	id	rcode	qname	qtype
172.17.0.10	8.8.8.8	59311	0	google.com.	1
172.17.0.10	8.8.8.8	35665	0	206.218.58.216.in-addr.arpa.	12
```

**Comment by pspacek** [comment]
I have no idea what went wrong, really. 

Log from whole session from autogen to an attempt to run example is attached here:
[typescript.log](https://github.com/DNS-OARC/dnsjit/files/1978932/typescript.log)

Envronment:
automake-1.15.1-2.fc27.noarch
libev-4.24-4.fc27.x86_64
libpcap-1.8.1-6.fc27.x86_64
luajit-2.1.0-0.6beta3.fc27.x86_64

Fedora 27 on x86_64. What did I forget? :-)

**Comment by jelu** [comment]
Your environment must be kaput:
```
$ docker pull fedora:27
$ docker run -it fedora:27 bash
$ yum update
$ yum group install -y "Development Tools"
$ yum install libpcap-devel libev-devel luajit-devel autoconf automake libtool
$ git clone https://github.com/DNS-OARC/dnsjit.git
$ cd dnsjit/
$ git submodule update --init
$ sh autogen.sh 
$ ./configure
$ make
$ make install
$ examples/dumpdns-qr.lua src/pcap-thread/hexdump/test/dns.pcap 
<< dnsjit v0.9.3 https://github.com/DNS-OARC/dnsjit/issues >>
src	dst	id	rcode	qname	qtype
172.17.0.10	8.8.8.8	59311	0	google.com.	1
172.17.0.10	8.8.8.8	35665	0	206.218.58.216.in-addr.arpa.	12
...
```

There is a few strange things with your output, `make` regenerates `config.h` and the order of compile is weird (not that it should matter). And most of your binaries are in `/bin`?

**Comment by pspacek** [comment]
Please accept my apology, it is my misconfiguration. I had bunch of Lua headers in /usr/local/include and for some reason (???) these caused the problem.

Different order of compilation is caused by my `MAKEFLAGS="-j4"` but it seems that this is not causing problems.
