### ISSUE TITLE
drool respdiff crashes with too large pcap's

### ISSUE THREAD

**Issue by RobinGeuze** [DNS-OARC/dnsjit#92]
If I feed drool respdiff a pcap with 1909 packet or more it produces the following error:

```
output.respdiff[0x40688428] fatal: mdb_put meta.version failed
```

**Comment by RobinGeuze** [comment]
Linux, Debian, stretch, dnsjit v0.9.5, drool v1.99.2, luajit:
```
ii  libluajit-5.1-2:amd64         2.0.4+dfsg-1+b1                amd64        Just in time compiler for Lua - library version
ii  libluajit-5.1-common          2.0.4+dfsg-1                   all          Just in time compiler for Lua - common files
```
Command output:
```
robing@respdiff0:~$ drool respdiff ~/respdiff-results old queries-small.pcap new xxx.xxx.xxx.xxx 53
<< dnsjit v0.9.5 https://github.com/DNS-OARC/dnsjit/issues >>
output.respdiff[0x40688428] fatal: mdb_put meta.version failed
```

That was the output I got earlier, interestingly, if the leveldb already exists created from a smaller dump it sometimes does appear to work. If I use it in such a working condition and put in a very large file (238 MB 10M packets) I get a segfault instead of this error.

**Comment by jelu** [comment]
Can you try removing the result folder before executing?

**Comment by RobinGeuze** [comment]
I did that, then it always crashes with pcap's over 1910 packets.

**Comment by jelu** [comment]
OK, I'm getting the segfault now, will look at this tomorrow.

**Comment by RobinGeuze** [comment]
So I did some digging myself. The mdb_put errors are caused by the fact that by default LMDB limits the map (and thus the DB) size to 10 MB. With 2K packets I already exceed that mapsize limit for some reason. It fixes itself if I add a mdb_env_set_mapsize with a size of 1 GB. The segfault still occurs though.

To solve the mdb_put errors, ideally you would catch "MDB_MAP_FULL" errors, close the transaction, increase the map size, possibly limited by some configurable maximum, and start a new transaction.

**Comment by RobinGeuze** [comment]
Nice, thank you very much :)

**Comment by jelu** [comment]
Packages are now available, use `--size` to set the database size.

**Comment by RobinGeuze** [comment]
Just tested and it works like a charm. Was still bothered by the segfault, however I managed to fix that by applying a tcpdump filter "not greater 1200" to my pcap, so its either a fragment or a large packet issue.

**Comment by jelu** [comment]
@RobinGeuze Hmm, if you can and if your allowed, could you send me the packets that cause segfaults? Email to jerry at dns-oarc.net

**Comment by RobinGeuze** [comment]
For some reason I cannot reproduce it with a newer (even bigger) dump I made, and I lost the old dump. I will probably do some more tests the coming few weeks, so if I run into it again I will let you know.
