### ISSUE TITLE
udp/tcp client: match QID of query and response

### ISSUE THREAD

**Issue by tomaskrizek** [DNS-OARC/dnsjit#99]
It would be useful to match QID of the response and ignore mismatching DNS messages. Currently, if an unexpected packet arrives while waiting for a response, it will be accepted.

This can happen if the server doesn't respond within the configured dnsjit timeout, but the response still arrives later. The original query will be marked as timeout, but when the answer still arrives later, it will be assigned to the current ongoing query. Its response will in turn be assigned to the next query. This will effectively shift all the remaining responses, causing them to be assigned to incorrect queries.

**Comment by jelu** [comment]
There is no matching of query and response done in the udp and tcp client.
Actually the clients don't care about receiving at all.

That is up to the code using the clients.

Or are you talking about some other part?

>

**Comment by tomaskrizek** [comment]
I see, I was looking at [examples/replay.lua](https://github.com/DNS-OARC/dnsjit/blob/develop/examples/replay.lua). Now when I think about it, it can be the responsibility of the code using the clients to handle the QID matching.
